# Generated by Django 5.1.3 on 2024-11-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_pdfs/'),
        ),
    ]
