# Generated by Django 5.1.3 on 2024-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_chapter_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='content_images',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(upload_to='chapter_pdfs/'),
        ),
    ]
